- name: Zipsa Main Project CI/CD
  hosts: localhost
  connection: local
  become: yes
  become_method: sudo
  vars_files: 
    - "vars/{{service_nm}}/{{env}}/params.yml"
  tasks: 
    - name: Init
      tags: [init]
      block: 
        - name: Make Shell Directory
          file: 
            path: "{{ dir.shell }}"
            state: directory
        - name: Move Jinja Files (test.sh)
          template:
            src: "shell/{{service_nm}}/{{env}}/test.sh.j2"
            dest: "{{ dir.shell }}/test.sh"
            mode: "0755"
        - name: Move Jinja Files (build.sh)
          template:
            src: "shell/{{service_nm}}/{{env}}/build.sh.j2"
            dest: "{{ dir.shell }}/build.sh"
            mode: "0755"
        - name: Move Jinja Files (build-docker.sh)
          template:
            src: "shell/{{service_nm}}/{{env}}/build-docker.sh.j2"
            dest: "{{ dir.shell }}/build-docker.sh"
            mode: "0755"
        - name: Move Jinja Files (push-ecr.sh)
          template:
            src: "shell/{{service_nm}}/{{env}}/push-ecr.sh.j2"
            dest: "{{ dir.shell }}/push-ecr.sh"
            mode: "0755"
    - name: Test Project
      tags: [test-project]
      block: 
        - name: Test Project
          shell: "./test.sh"
          args:
            chdir: "{{ dir.shell }}"
    - name: Build Project
      tags: [build-project]
      block: 
        - name: Build Project
          shell: "./build.sh"
          args:
            chdir: "{{ dir.shell }}"
    - name: Build Docker Image
      tags: [build-docker-image]
      block: 
        - name: Build Docker Image
          shell: "./build-docker.sh"
          args:
            chdir: "{{ dir.shell }}"
    - name: Push Docker Image
      tags: [push-docker-image]
      block: 
        - name: Push Docker Image
          shell: "./push-ecr.sh"
          args:
            chdir: "{{ dir.shell }}"
    - name: Create Task Definition
      tags: [create-task]
      block: 
        - name: Create Task Definition
          ecs_taskdefinition: 
            aws_access_key: "{{ aws.credentials.aws_access_key_id }}"
            aws_secret_key: "{{ aws.credentials.aws_secret_access_key }}"
            containers: 
            - name: "{{ aws.ecs.container_name }}"
              essential: yes
              image: "{{ aws.ecr.url }}/{{ aws.ecr.name }}:{{image_name}}-{{env}}-{{image_tag}}"
              healthCheck: 
                command: 
                - "CMD-SHELL"
                - "curl -H 'Authorization: Bearer' http://localhost:8080/api/healthcheck/task"
                interval: 300
                timeout: 60
                retries: 3
                startPeriod: 300
              mountPoints: 
              - containerPath: "{{ aws.log_mount.container }}"
                readOnly: no
                sourceVolume: zipsa-mount
              portMappings: 
              - containerPort: "{{ port.service }}"
                hostPort: "{{ port.host }}"
                protocol: tcp
            family: "{{task_definition_name}}"
            cpu: "1024"
            memory: "512"
            launch_type: EC2
            region: "{{ aws.region }}"
            state: present
            volumes: 
              - name: zipsa-mount
                host: 
                  sourcePath: "{{ aws.log_mount.host }}"
    - name: Delete Service
      tags: [delete-service]
      block:
        - name: Stop Task
          ecs_service: 
            load_balancers:
              - containerPort: "{{ port.service }}"
                containerName: "{{ aws.ecs.container_name }}"
                targetGroupArn: "{{ aws.alb.target_group_arn }}"
            name: "{{ aws.ecs.service_name }}"
            aws_access_key: "{{ aws.credentials.aws_access_key_id }}"
            aws_secret_key: "{{ aws.credentials.aws_secret_access_key }}"
            state: present
            cluster: "{{ aws.ecs.cluster_name }}"
            launch_type: EC2
            region: "{{ aws.region }}"
            task_definition: "{{task_definition_name}}"
            desired_count: 0
            scheduling_strategy: REPLICA
            deployment_configuration: 
              deployment_circuit_breaker: 
                enable: no
                rollback: no
              minimum_healthy_percent: 100
              maximum_percent: 200
        - name: Wait 5 Minutes
          pause:
            minutes: 5
        - name: Delete Service
          ecs_service:
            name: "{{ aws.ecs.service_name }}"
            aws_access_key: "{{ aws.credentials.aws_access_key_id }}"
            aws_secret_key: "{{ aws.credentials.aws_secret_access_key }}"
            state: absent
            cluster: "{{ aws.ecs.cluster_name }}"
    - name: Create Service
      tags: [create-service]
      block:
        - name: Start Service
          ecs_service: 
            load_balancers:
              - containerPort: "{{ port.service }}"
                containerName: "{{ aws.ecs.container_name }}"
                targetGroupArn: "{{ aws.alb.target_group_arn }}"
            name: "{{ aws.ecs.service_name }}"
            aws_access_key: "{{ aws.credentials.aws_access_key_id }}"
            aws_secret_key: "{{ aws.credentials.aws_secret_access_key }}"
            state: present
            cluster: "{{ aws.ecs.cluster_name }}"
            launch_type: EC2
            region: "{{ aws.region }}"
            task_definition: "{{task_definition_name}}"
            desired_count: 1 
            scheduling_strategy: REPLICA
            deployment_configuration: 
              deployment_circuit_breaker: 
                enable: no
                rollback: no
              minimum_healthy_percent: 100
              maximum_percent: 200